# This file configures the image-classif app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: image-classif-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-classif
  template:
    metadata:
      labels:
        app: image-classif
    spec:
      containers:
      - name: image-classif-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/apple-assignment-280918/image-classif:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"