# This file configures the image-classif app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: image-classif-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-classif
  template:
    metadata:
      labels:
        app: image-classif
    spec:
      containers:
      - name: image-classif-app
        image: gcr.io/apple-assignment-280918/image-classif:latest
        imagePullPolicy: "Always"
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/google-cloud-api-key.json
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google

      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=apple-assignment-280918:us-central1:image-classification=tcp:5432",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: my-secrets-volume
            mountPath: /secrets/cloudsql
            readOnly: true
      volumes:
        - name: my-secrets-volume
          secret:
            secretName: cloudsql-instance-credentials
        - name: google-cloud-key
          secret:
            secretName: cloud-storage