# Load balancer proxy over image classifier svc. 
# By specifying the type as a 'LoadBalancer', Kubernetes Engine will
# create an external HTTP load balancer.
apiVersion: v1
kind: Service
metadata:
  name: image-classif-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: image-classif
  ports:
  - port: 80
    targetPort: 8080